#include <iostream>
using namespace std;
int main()
{
cout << "Nama saya Andhi Prasetyo, NIM. C20010004 \n";
cout << "Saya tinggal di wilayah Kecamatan Cepogo. \n";
cout << "Sebelum saya melanjutkan kuliah TI di UBY,\n";
cout << "saya sekolah di SMA Negeri 1 Boyolali \n";
cout << "Saat ini selain saya kuliah, \n";
cout << "saya juga mengabdi di Pemerintah Desa Sumbung \n";
cout << "sebagai Kasie Pemerintahan. \n";
return 0;
}
